######################### RELOAD SHELL, BASH PROFILE  #########################
alias r!='exec $SHELL -l'
[[ ! -L  "$HOME/.profile" ]] && alias r.='source ~/.bashrc' || alias r.='source ~/.profile'

######################### ALL PURPOSE #########################
alias ..='cd ..'
alias *='code -n .'
alias @='cat /etc/hosts | grep'
alias @.='sudo nano /etc/hosts'
alias a='alias'
alias a?='alias | grep'
alias b='cd -'
alias c='clear'
alias d='du -hc -d 1'
alias h='history'
alias h?='history | grep --color=auto'
alias h!='history -wc'
alias ip?='ipconfig getifaddr en0'
alias ip??='dig +short myip.opendns.com @resolver1.opendns.com'
alias la='ls -lFAhG'
alias ll='ls -lFhG'
alias lln='ls -lthG'
alias llx='ls -lthGS'
alias lt='ls -1 | wc -l'
alias tmz='sudo rm /var/mail/$(whoami)'
alias xf='rsync -rvzu --progress'
alias xf?='rsync -rvzu --progress --dry-run'
alias z='rm -rf'
# END OF FILE
